<template>
    <section class="flex relative overflow-scroll">
        <div class="sticky top-10 flex-1"><p>Some Sticky Text</p></div>
        <section class="flex-1">
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur sint iusto amet! Necessitatibus animi minus error nostrum est totam repellendus, aspernatur dicta tempore ullam! Iusto tempore voluptates similique harum voluptatibus molestiae cum dignissimos ipsam fugit aspernatur esse voluptatem qui soluta dolore voluptate nobis quibusdam, enim magni asperiores ullam at non doloribus nemo ab. Iste, vel distinctio. Deleniti nulla tempore nesciunt quisquam recusandae consequatur beatae. Velit magni, aliquid perspiciatis, neque vero necessitatibus omnis rerum odio, dolorum natus optio unde perferendis animi impedit rem placeat deleniti aliquam harum. Quis pariatur, nesciunt nobis minus, fuga numquam aut, laudantium id recusandae consequatur aliquam ducimus.</div>
        <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur sint iusto amet! Necessitatibus animi minus error nostrum est totam repellendus, aspernatur dicta tempore ullam! Iusto tempore voluptates similique harum voluptatibus molestiae cum dignissimos ipsam fugit aspernatur esse voluptatem qui soluta dolore voluptate nobis quibusdam, enim magni asperiores ullam at non doloribus nemo ab. Iste, vel distinctio. Deleniti nulla tempore nesciunt quisquam recusandae consequatur beatae. Velit magni, aliquid perspiciatis, neque vero necessitatibus omnis rerum odio, dolorum natus optio unde perferendis animi impedit rem placeat deleniti aliquam harum. Quis pariatur, nesciunt nobis minus, fuga numquam aut, laudantium id recusandae consequatur aliquam ducimus.</div>
        <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur sint iusto amet! Necessitatibus animi minus error nostrum est totam repellendus, aspernatur dicta tempore ullam! Iusto tempore voluptates similique harum voluptatibus molestiae cum dignissimos ipsam fugit aspernatur esse voluptatem qui soluta dolore voluptate nobis quibusdam, enim magni asperiores ullam at non doloribus nemo ab. Iste, vel distinctio. Deleniti nulla tempore nesciunt quisquam recusandae consequatur beatae. Velit magni, aliquid perspiciatis, neque vero necessitatibus omnis rerum odio, dolorum natus optio unde perferendis animi impedit rem placeat deleniti aliquam harum. Quis pariatur, nesciunt nobis minus, fuga numquam aut, laudantium id recusandae consequatur aliquam ducimus.</div>
        <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur sint iusto amet! Necessitatibus animi minus error nostrum est totam repellendus, aspernatur dicta tempore ullam! Iusto tempore voluptates similique harum voluptatibus molestiae cum dignissimos ipsam fugit aspernatur esse voluptatem qui soluta dolore voluptate nobis quibusdam, enim magni asperiores ullam at non doloribus nemo ab. Iste, vel distinctio. Deleniti nulla tempore nesciunt quisquam recusandae consequatur beatae. Velit magni, aliquid perspiciatis, neque vero necessitatibus omnis rerum odio, dolorum natus optio unde perferendis animi impedit rem placeat deleniti aliquam harum. Quis pariatur, nesciunt nobis minus, fuga numquam aut, laudantium id recusandae consequatur aliquam ducimus.</div>
        <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur sint iusto amet! Necessitatibus animi minus error nostrum est totam repellendus, aspernatur dicta tempore ullam! Iusto tempore voluptates similique harum voluptatibus molestiae cum dignissimos ipsam fugit aspernatur esse voluptatem qui soluta dolore voluptate nobis quibusdam, enim magni asperiores ullam at non doloribus nemo ab. Iste, vel distinctio. Deleniti nulla tempore nesciunt quisquam recusandae consequatur beatae. Velit magni, aliquid perspiciatis, neque vero necessitatibus omnis rerum odio, dolorum natus optio unde perferendis animi impedit rem placeat deleniti aliquam harum. Quis pariatur, nesciunt nobis minus, fuga numquam aut, laudantium id recusandae consequatur aliquam ducimus.</div>
        </section>
    </section>
</template>